# Generated by Django 4.2.21 on 2025-05-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrama', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aluno',
            table='alunos',
        ),
    ]
